{"name": "To Check the functionality of Accept_Page With Valid & Invalid Data.", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//a[text()='Confirm']\"}\n  (Session info: chrome=94.0.4606.81)\nStacktrace:\nBacktrace:\n\tOrdinal0 [0x00A0BDE3+2473443]\n\tOrdinal0 [0x009A6661+2057825]\n\tOrdinal0 [0x008B2438+1057848]\n\tOrdinal0 [0x008DC7DB+1230811]\n\tOrdinal0 [0x00906712+1402642]\n\tOrdinal0 [0x008F571A+1333018]\n\tOrdinal0 [0x00904ABF+1395391]\n\tOrdinal0 [0x008F55AB+1332651]\n\tOrdinal0 [0x008D2104+1188100]\n\tOrdinal0 [0x008D2F59+1191769]\n\tGetHandleVerifier [0x00B92266+1549718]\n\tGetHandleVerifier [0x00C3D4A7+2250711]\n\tGetHandleVerifier [0x00A9718B+521403]\n\tGetHandleVerifier [0x00A96229+517465]\n\tOrdinal0 [0x009AB79D+2078621]\n\tOrdinal0 [0x009AFB58+2095960]\n\tOrdinal0 [0x009AFC92+2096274]\n\tOrdinal0 [0x009B9541+2135361]\n\tBaseThreadInitThunk [0x7617FA29+25]\n\tRtlGetAppContainerNamedObjectPath [0x77E57A7E+286]\n\tRtlGetAppContainerNamedObjectPath [0x77E57A4E+238]\n\n", "trace": "  File \"C:\\Python39\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Python39\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"Feature\\steps\\StepDefination.py\", line 191, in step_impl\n    Confrom_button=context.driver2.find_element_by_xpath(\"//a[text()='Confirm']\")\n  File \"C:\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 514, in find_element_by_xpath\n    return self.find_element(by=By.XPATH, value=xpath)\n  File \"C:\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 1238, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"C:\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 418, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given User Friend open Browser, Enter Url, Navigate To Log_in Page", "status": "passed", "start": 1634815222251, "stop": 1634815264327}, {"name": "When User Friend Enter Username With Invalid Data", "status": "passed", "start": 1634815264327, "stop": 1634815265783}, {"name": "And User Friend Click On start Button", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//a[text()='Confirm']\"}\n  (Session info: chrome=94.0.4606.81)\nStacktrace:\nBacktrace:\n\tOrdinal0 [0x00A0BDE3+2473443]\n\tOrdinal0 [0x009A6661+2057825]\n\tOrdinal0 [0x008B2438+1057848]\n\tOrdinal0 [0x008DC7DB+1230811]\n\tOrdinal0 [0x00906712+1402642]\n\tOrdinal0 [0x008F571A+1333018]\n\tOrdinal0 [0x00904ABF+1395391]\n\tOrdinal0 [0x008F55AB+1332651]\n\tOrdinal0 [0x008D2104+1188100]\n\tOrdinal0 [0x008D2F59+1191769]\n\tGetHandleVerifier [0x00B92266+1549718]\n\tGetHandleVerifier [0x00C3D4A7+2250711]\n\tGetHandleVerifier [0x00A9718B+521403]\n\tGetHandleVerifier [0x00A96229+517465]\n\tOrdinal0 [0x009AB79D+2078621]\n\tOrdinal0 [0x009AFB58+2095960]\n\tOrdinal0 [0x009AFC92+2096274]\n\tOrdinal0 [0x009B9541+2135361]\n\tBaseThreadInitThunk [0x7617FA29+25]\n\tRtlGetAppContainerNamedObjectPath [0x77E57A7E+286]\n\tRtlGetAppContainerNamedObjectPath [0x77E57A4E+238]\n\n", "trace": "  File \"C:\\Python39\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Python39\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"Feature\\steps\\StepDefination.py\", line 191, in step_impl\n    Confrom_button=context.driver2.find_element_by_xpath(\"//a[text()='Confirm']\")\n  File \"C:\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 514, in find_element_by_xpath\n    return self.find_element(by=By.XPATH, value=xpath)\n  File \"C:\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 1238, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"C:\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 418, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1634815265783, "stop": 1634815275844}, {"name": "And User Friend Validate onesignal pop-up functionality With click on Later Button", "status": "skipped", "start": 1634815275845, "stop": 1634815275845}, {"name": "And User Friend Enter Username With Valid Data", "status": "skipped", "start": 1634815275845, "stop": 1634815275845}, {"name": "And User Friend Click on Start Buttons", "status": "skipped", "start": 1634815275845, "stop": 1634815275845}, {"name": "Then User Friend Should be Navigate to Answer Page  Successfully", "status": "skipped", "start": 1634815275845, "stop": 1634815275845}], "start": 1634815222249, "stop": 1634815275845, "uuid": "d911973f-263e-4c46-8e03-1ff85400f1ab", "historyId": "03c917ac6824ab0c8e6cc20d4dd5291a", "fullName": "Wowdare User Side End to End Functionality: To Check the functionality of Accept_Page With Valid & Invalid Data.", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "Accept_Page"}, {"name": "feature", "value": "Wowdare User Side End to End Functionality"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}